basePath: /
host: localhost:8081
info:
  contact:
    email: your-email@example.com
    name: Goutam Parmar
  description: This is a Todo management API server built with Golang.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Todo App API
  version: "1.0"
paths: {}
swagger: "2.0"
